<a href="https://colab.research.google.com/github/NayeemaNonta/RatemyprofessorsMLProject/blob/main/Unsupervised_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing and Setup

In [ ]:
# Import necessary python libraries
import pandas as pd
import csv
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
# upload Rate My Professor data for exploration
from google.colab import files 
uploaded_files = files.upload() # upload file

Saving RateMyProfessor_Sample_data.csv to RateMyProfessor_Sample_data.csv

In [ ]:
import io
data = io.BytesIO(uploaded_files['RateMyProfessor_Sample_data.csv']) # read file

In [ ]:
# load as a data frame
df = pd.read_csv(data) 

# view the first 5 rows to get an initial idea of the columns
df.head()

,professor_name,school_name,department_name,local_name,state_name,year_since_first_review,star_rating,take_again,diff_index,tag_professor,...,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes,IsCourseOnline
0,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
1,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
2,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
3,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
4,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0

#Data Preprocessing: Step 1
Keeping only unique instances of the Professor Name column

In [ ]:
# output the count of all rows in the dataset before any modifications are made
print("Count before Removing Duplicates: ")
df.count()

Count before Removing Duplicates:

professor_name              20000
school_name                 20000
department_name             20000
local_name                  20000
state_name                  20000
year_since_first_review     20000
star_rating                 20000
take_again                   2998
diff_index                  20000
tag_professor               11093
num_student                 20000
post_date                   19995
name_onlines                20000
name_not_onlines            19995
student_star                19995
student_difficult           19995
attence                      4009
for_credits                  4053
would_take_agains            2582
grades                       3292
help_useful                 20000
help_not_useful             20000
comments                    19993
word_comment                19993
gender                      20000
race                        20000
asian                       20000
hispanic                    20000
nh_black                    20000
nh_white                    20000
gives_good_feedback         20000
caring                      20000
respected                   20000
participation_matters       20000
clear_grading_criteria      20000
skip_class                  20000
amazing_lectures            20000
inspirational               20000
tough_grader                20000
hilarious                   20000
get_ready_to_read           20000
lots_of_homework            20000
accessible_outside_class    20000
lecture_heavy               20000
extra_credit                20000
graded_by_few_things        20000
group_projects              20000
test_heavy                  20000
so_many_papers              20000
beware_of_pop_quizzes       20000
IsCourseOnline              20000
dtype: int64

In [ ]:
# output the first 5 rows of dataset 
df.head()

# Note: all Profs listed here the same Prof with the same 'star_rating' value

,professor_name,school_name,department_name,local_name,state_name,year_since_first_review,star_rating,take_again,diff_index,tag_professor,...,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes,IsCourseOnline
0,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
1,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
2,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
3,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
4,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
# remove rows that have a duplicate Professor Name
ab = df.drop_duplicates(subset='professor_name', keep='first')

# output the count of all rows in the dataset after removing duplicates 
print("Count after Removing Duplicates: ")
ab.count()

Count after Removing Duplicates:

professor_name              1413
school_name                 1413
department_name             1413
local_name                  1413
state_name                  1413
year_since_first_review     1413
star_rating                 1413
take_again                   151
diff_index                  1413
tag_professor                626
num_student                 1413
post_date                   1413
name_onlines                1413
name_not_onlines            1413
student_star                1413
student_difficult           1413
attence                      589
for_credits                  635
would_take_agains            508
grades                       480
help_useful                 1413
help_not_useful             1413
comments                    1412
word_comment                1412
gender                      1413
race                        1413
asian                       1413
hispanic                    1413
nh_black                    1413
nh_white                    1413
gives_good_feedback         1413
caring                      1413
respected                   1413
participation_matters       1413
clear_grading_criteria      1413
skip_class                  1413
amazing_lectures            1413
inspirational               1413
tough_grader                1413
hilarious                   1413
get_ready_to_read           1413
lots_of_homework            1413
accessible_outside_class    1413
lecture_heavy               1413
extra_credit                1413
graded_by_few_things        1413
group_projects              1413
test_heavy                  1413
so_many_papers              1413
beware_of_pop_quizzes       1413
IsCourseOnline              1413
dtype: int64

In [ ]:
# output the first 5 rows of dataset 
ab.head()

# Note: all Profs listed here are different with different 'star_rating' values

,professor_name,school_name,department_name,local_name,state_name,year_since_first_review,star_rating,take_again,diff_index,tag_professor,...,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes,IsCourseOnline
0,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
20,Jans Wager,Utah Valley University,English department,Orem,UT,11,4.5,0.83,3.0,Gives good feedback (6) Participation matters...,...,0,0,0,0,1,1,0,0,0,0
40,Robert Warden,Philadelphia University,Writing department,Philadelphia,PA,2,3.4,NaN,2.8,NaN,...,0,0,0,0,0,0,0,0,0,0
48,Bryan Eldredge,Utah Valley University,ASL & Deaf Studies department,Orem,UT,14,4.2,NaN,3.3,Tough Grader (2) Participation matters (2) L...,...,0,0,1,0,0,0,1,0,0,1
66,William Hollinrake,Des Moines Area Community College,Computer Science department,Ankeny,IA,6,1.6,NaN,4.3,Tough Grader (10) Skip class? You won\'t pass...,...,0,0,0,0,0,0,0,0,0,0

#Data Preprocessing: Step 2
Dropping rows where there are nulls in "tag_professor" column. This is important because otherwise it will overinflate the '0' values for the 20 binary Professor Characteristics columns such that meaningful predictions may not be made.

In [ ]:
# output the count of all rows in the dataset before any modifications are made
print("Count before dropping:\n", ab.count(), "\n")

Count before dropping:
 professor_name              1413
school_name                 1413
department_name             1413
local_name                  1413
state_name                  1413
year_since_first_review     1413
star_rating                 1413
take_again                   151
diff_index                  1413
tag_professor                626
num_student                 1413
post_date                   1413
name_onlines                1413
name_not_onlines            1413
student_star                1413
student_difficult           1413
attence                      589
for_credits                  635
would_take_agains            508
grades                       480
help_useful                 1413
help_not_useful             1413
comments                    1412
word_comment                1412
gender                      1413
race                        1413
asian                       1413
hispanic                    1413
nh_black                    1413
nh_white                    1413
gives_good_feedback         1413
caring                      1413
respected                   1413
participation_matters       1413
clear_grading_criteria      1413
skip_class                  1413
amazing_lectures            1413
inspirational               1413
tough_grader                1413
hilarious                   1413
get_ready_to_read           1413
lots_of_homework            1413
accessible_outside_class    1413
lecture_heavy               1413
extra_credit                1413
graded_by_few_things        1413
group_projects              1413
test_heavy                  1413
so_many_papers              1413
beware_of_pop_quizzes       1413
IsCourseOnline              1413
dtype: int64

In [ ]:
# dropping rows if there are missing values present in tag_professor
cd = ab.dropna(subset=['tag_professor'])
# output the count of all rows in the dataset after the modifications are made
print("Count after dropping:\n", cd.count())

Count after dropping:
 professor_name              626
school_name                 626
department_name             626
local_name                  626
state_name                  626
year_since_first_review     626
star_rating                 626
take_again                  151
diff_index                  626
tag_professor               626
num_student                 626
post_date                   626
name_onlines                626
name_not_onlines            626
student_star                626
student_difficult           626
attence                     517
for_credits                 605
would_take_agains           499
grades                      424
help_useful                 626
help_not_useful             626
comments                    626
word_comment                626
gender                      626
race                        626
asian                       626
hispanic                    626
nh_black                    626
nh_white                    626
gives_good_feedback         626
caring                      626
respected                   626
participation_matters       626
clear_grading_criteria      626
skip_class                  626
amazing_lectures            626
inspirational               626
tough_grader                626
hilarious                   626
get_ready_to_read           626
lots_of_homework            626
accessible_outside_class    626
lecture_heavy               626
extra_credit                626
graded_by_few_things        626
group_projects              626
test_heavy                  626
so_many_papers              626
beware_of_pop_quizzes       626
IsCourseOnline              626
dtype: int64

#Data Preprocessing: Step 3
Developing 2 new datasets: Good Professors vs Bad Professors. 
Professors with a rating greater than 4.0 will be considered Good Professors and Professors with a Rating under 2.9 will be considered Bad Professors. All Professors with ratings 3.0 to 3.9 will be omitted.

In [ ]:
# output the first 5 rows of dataset 
cd.head()

# Note: 1 Prof (William Hollinrake) listed here has a star_rating of 1.6 making him a Bad Professor
# Note: The rest 4 Profs are considered Good Professors as their star_rating is above 4.0

,professor_name,school_name,department_name,local_name,state_name,year_since_first_review,star_rating,take_again,diff_index,tag_professor,...,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes,IsCourseOnline
0,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
20,Jans Wager,Utah Valley University,English department,Orem,UT,11,4.5,0.83,3.0,Gives good feedback (6) Participation matters...,...,0,0,0,0,1,1,0,0,0,0
48,Bryan Eldredge,Utah Valley University,ASL & Deaf Studies department,Orem,UT,14,4.2,NaN,3.3,Tough Grader (2) Participation matters (2) L...,...,0,0,1,0,0,0,1,0,0,1
66,William Hollinrake,Des Moines Area Community College,Computer Science department,Ankeny,IA,6,1.6,NaN,4.3,Tough Grader (10) Skip class? You won\'t pass...,...,0,0,0,0,0,0,0,0,0,0
106,Deborah Pluss,William Paterson University,Communication department,Wayne,NJ,14,4.1,NaN,2.1,LECTURE HEAVY (3) LOTS OF HOMEWORK (2) Tough...,...,1,0,1,0,0,1,0,0,0,0

In [ ]:
# bad profs are rated from 4.0-5.0 (star_rating column)
# finding values where the professors are rated under 4.0 are dropped 
goodProfs = cd.drop(cd[cd.star_rating < 4.0].index) 

# counting the number of Good Professors in the dataset
goodProfs.count() #283 rows of data

professor_name              283
school_name                 283
department_name             283
local_name                  283
state_name                  283
year_since_first_review     283
star_rating                 283
take_again                   64
diff_index                  283
tag_professor               283
num_student                 283
post_date                   283
name_onlines                283
name_not_onlines            283
student_star                283
student_difficult           283
attence                     230
for_credits                 273
would_take_agains           231
grades                      193
help_useful                 283
help_not_useful             283
comments                    283
word_comment                283
gender                      283
race                        283
asian                       283
hispanic                    283
nh_black                    283
nh_white                    283
gives_good_feedback         283
caring                      283
respected                   283
participation_matters       283
clear_grading_criteria      283
skip_class                  283
amazing_lectures            283
inspirational               283
tough_grader                283
hilarious                   283
get_ready_to_read           283
lots_of_homework            283
accessible_outside_class    283
lecture_heavy               283
extra_credit                283
graded_by_few_things        283
group_projects              283
test_heavy                  283
so_many_papers              283
beware_of_pop_quizzes       283
IsCourseOnline              283
dtype: int64

In [ ]:
# output the first 5 rows of Good Profs dataset 
goodProfs.head()

# Note: Now all Profs listed here has a star_rating greater than or equal to 4.0 making them Good Professors

,professor_name,school_name,department_name,local_name,state_name,year_since_first_review,star_rating,take_again,diff_index,tag_professor,...,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes,IsCourseOnline
0,Leslie Looney,University Of Illinois at Urbana-Champaign,Astronomy department,Champaign\xe2\x80\x93Urbana,IL,11,4.7,NaN,2.0,Hilarious (2) GROUP PROJECTS (2) Gives good ...,...,0,0,0,0,0,1,0,0,0,0
20,Jans Wager,Utah Valley University,English department,Orem,UT,11,4.5,0.83,3.0,Gives good feedback (6) Participation matters...,...,0,0,0,0,1,1,0,0,0,0
48,Bryan Eldredge,Utah Valley University,ASL & Deaf Studies department,Orem,UT,14,4.2,NaN,3.3,Tough Grader (2) Participation matters (2) L...,...,0,0,1,0,0,0,1,0,0,1
106,Deborah Pluss,William Paterson University,Communication department,Wayne,NJ,14,4.1,NaN,2.1,LECTURE HEAVY (3) LOTS OF HOMEWORK (2) Tough...,...,1,0,1,0,0,1,0,0,0,0
243,Hon Linda,University of Florida,Communication department,Gainesville,FL,11,4.8,NaN,3.3,Inspirational (1) Respected (1),...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# bad profs are rated from 1.0-2.9 (star_rating column)
# finding values where the professors are rated above or equal to 3.0 and dropping them
badProfs = cd.drop(cd[cd.star_rating >= 3.0].index) 

# counting the number of Bad Professors in the dataset
badProfs.count() #99 rows of data

professor_name              99
school_name                 99
department_name             99
local_name                  99
state_name                  99
year_since_first_review     99
star_rating                 99
take_again                  25
diff_index                  99
tag_professor               99
num_student                 99
post_date                   99
name_onlines                99
name_not_onlines            99
student_star                99
student_difficult           99
attence                     85
for_credits                 96
would_take_agains           73
grades                      58
help_useful                 99
help_not_useful             99
comments                    99
word_comment                99
gender                      99
race                        99
asian                       99
hispanic                    99
nh_black                    99
nh_white                    99
gives_good_feedback         99
caring                      99
respected                   99
participation_matters       99
clear_grading_criteria      99
skip_class                  99
amazing_lectures            99
inspirational               99
tough_grader                99
hilarious                   99
get_ready_to_read           99
lots_of_homework            99
accessible_outside_class    99
lecture_heavy               99
extra_credit                99
graded_by_few_things        99
group_projects              99
test_heavy                  99
so_many_papers              99
beware_of_pop_quizzes       99
IsCourseOnline              99
dtype: int64

In [ ]:
# output the first 5 rows of Bad Profs dataset 
badProfs.head()

# Note: Now all Profs listed here has a star_rating less than or equal to 2.9 making them Good Professors

,professor_name,school_name,department_name,local_name,state_name,year_since_first_review,star_rating,take_again,diff_index,tag_professor,...,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes,IsCourseOnline
66,William Hollinrake,Des Moines Area Community College,Computer Science department,Ankeny,IA,6,1.6,NaN,4.3,Tough Grader (10) Skip class? You won\'t pass...,...,0,0,0,0,0,0,0,0,0,0
281,John Cunningham,Skidmore College,Fine Arts department,Saratoga Springs,NY,13,2.6,NaN,3.3,Caring (2) ACCESSIBLE OUTSIDE CLASS (1) Insp...,...,0,1,0,0,0,0,0,0,0,0
475,Joan Krone,Denison University,Computer Science department,Granville,OH,14,2.4,NaN,3.0,Caring (1) LECTURE HEAVY (1),...,0,0,1,0,0,0,0,0,0,0
892,Matthew Erdelyi,Brooklyn College,Psychology department,Brooklyn,NY,3,2.6,NaN,2.9,Get ready to read (8) Tough Grader (4) LECTU...,...,0,0,1,0,1,0,1,0,0,0
912,Harihar Khanal,Embry-Riddle Aeronautical University,Mathematics department,Daytona Beach,FL,9,2.9,NaN,3.2,LECTURE HEAVY (3) Tough Grader (2) LOTS OF H...,...,1,0,1,1,0,1,0,0,0,0

#Data Preprocessing: Step 4
Creating the final 2 datasets by only including the 20 boolean Characteristics for both the Good Profs and Bad Profs.

In [ ]:
# converting the goodProfs and badProfs datasets to CSV files for reference
goodProfs.to_csv('good_profs.csv')
badProfs.to_csv('bad_profs.csv')

In [ ]:
# including only the boolean columns of tags for good professor
goodProfsBooleanTags = goodProfs[['gives_good_feedback', 'caring', 'respected', 'participation_matters', 'clear_grading_criteria', 'skip_class', 'amazing_lectures', 'inspirational', 'tough_grader', 'hilarious', 'get_ready_to_read', 'lots_of_homework', 'accessible_outside_class', 'lecture_heavy', 'extra_credit', 'graded_by_few_things', 'group_projects', 'test_heavy', 'so_many_papers', 'beware_of_pop_quizzes']]
# converting the goodProfsBooleanTags to CSV files for reference
goodProfsBooleanTags.to_csv('good_profs_boolean_tags.csv')

In [ ]:
# output the first 5 rows of Good Profs boolean tags dataset 
goodProfsBooleanTags.head()

,gives_good_feedback,caring,respected,participation_matters,clear_grading_criteria,skip_class,amazing_lectures,inspirational,tough_grader,hilarious,get_ready_to_read,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes
0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
20,1,1,1,1,1,1,1,0,1,1,1,0,0,0,0,1,1,0,0,0
48,0,0,0,1,0,0,0,1,1,1,0,0,0,1,0,0,0,1,0,0
106,0,1,0,0,0,1,0,0,1,1,1,1,0,1,0,0,1,0,0,0
243,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# including only the boolean columns of tags for good professor
badProfsBooleanTags = badProfs[['gives_good_feedback', 'caring', 'respected', 'participation_matters', 'clear_grading_criteria', 'skip_class', 'amazing_lectures', 'inspirational', 'tough_grader', 'hilarious', 'get_ready_to_read', 'lots_of_homework', 'accessible_outside_class', 'lecture_heavy', 'extra_credit', 'graded_by_few_things', 'group_projects', 'test_heavy', 'so_many_papers', 'beware_of_pop_quizzes']]
# converting the badProfsBooleanTags to CSV files for reference
badProfsBooleanTags.to_csv('bad_profs_boolean_tags.csv')

In [ ]:
# output the first 5 rows of Good Profs boolean tags dataset 
badProfsBooleanTags.head()

,gives_good_feedback,caring,respected,participation_matters,clear_grading_criteria,skip_class,amazing_lectures,inspirational,tough_grader,hilarious,get_ready_to_read,lots_of_homework,accessible_outside_class,lecture_heavy,extra_credit,graded_by_few_things,group_projects,test_heavy,so_many_papers,beware_of_pop_quizzes
66,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0
281,0,1,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0
475,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
892,0,0,0,0,1,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0
912,0,0,1,0,1,1,0,0,1,0,0,1,0,1,1,0,1,0,0,0

# **Association Rules: Good Profs**
4 experiments will be done to understand interesting correlations between Characteristics of Good Professors

1. Low support and Low confidence
2. Low support and High confidence
3. High support and Low confidence
4. High support and High confidence

###*EXPERIMENT 1: Low support and Low confidence*

In [ ]:
# GOOD PROFS:
# find all itemsets that have a minimum support of 10%
frequent_itemsets_good = apriori(goodProfsBooleanTags,min_support=0.1,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_good)

      support                                           itemsets
0    0.600707                              (gives_good_feedback)
1    0.554770                                           (caring)
2    0.636042                                        (respected)
3    0.388693                            (participation_matters)
4    0.385159                           (clear_grading_criteria)
..        ...                                                ...
870  0.106007  (clear_grading_criteria, respected, hilarious,...
871  0.116608  (clear_grading_criteria, respected, inspiratio...
872  0.102473  (respected, inspirational, hilarious, skip_cla...
873  0.102473  (respected, tough_grader, hilarious, skip_clas...
874  0.109541  (clear_grading_criteria, respected, amazing_le...

[875 rows x 2 columns]

In [ ]:
# GOOD PROFS:
# find association rules that have confidence >= 10%
rules_good_prof = association_rules(frequent_itemsets_good,metric='confidence',min_threshold=0.1)

# print the association rules, their support, and confidence
print(rules_good_prof[['antecedents','consequents','support','confidence']])

                   antecedents  \
0                     (caring)
1        (gives_good_feedback)
2                  (respected)
3        (gives_good_feedback)
4      (participation_matters)
...                        ...
11629       (amazing_lectures)
11630          (inspirational)
11631              (hilarious)
11632                 (caring)
11633    (gives_good_feedback)

                                             consequents   support  confidence
0                                  (gives_good_feedback)  0.385159    0.694268
1                                               (caring)  0.385159    0.641176
2                                  (gives_good_feedback)  0.431095    0.677778
3                                            (respected)  0.431095    0.717647
4                                  (gives_good_feedback)  0.275618    0.709091
...                                                  ...       ...         ...
11629  (clear_grading_criteria, respected, inspiratio...  0.109541    0.252033
11630  (clear_grading_criteria, gives_good_feedback, ...  0.109541    0.234848
11631  (clear_grading_criteria, gives_good_feedback, ...  0.109541    0.254098
11632  (clear_grading_criteria, gives_good_feedback, ...  0.109541    0.197452
11633  (clear_grading_criteria, respected, inspiratio...  0.109541    0.182353

[11634 rows x 4 columns]

### *EXPERIMENT 2: Low support and High confidence*

In [ ]:
# GOOD PROFS:
# find all itemsets that have a minimum support of 25%
frequent_itemsets_good = apriori(goodProfsBooleanTags,min_support=0.25,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_good)

     support                                           itemsets
0   0.600707                              (gives_good_feedback)
1   0.554770                                           (caring)
2   0.636042                                        (respected)
3   0.388693                            (participation_matters)
4   0.385159                           (clear_grading_criteria)
5   0.402827                                       (skip_class)
6   0.434629                                 (amazing_lectures)
7   0.466431                                    (inspirational)
8   0.416961                                     (tough_grader)
9   0.431095                                        (hilarious)
10  0.349823                                (get_ready_to_read)
11  0.250883                                 (lots_of_homework)
12  0.250883                         (accessible_outside_class)
13  0.268551                                    (lecture_heavy)
14  0.385159                      (caring, gives_good_feedback)
15  0.431095                   (respected, gives_good_feedback)
16  0.275618       (participation_matters, gives_good_feedback)
17  0.293286      (clear_grading_criteria, gives_good_feedback)
18  0.286219                  (skip_class, gives_good_feedback)
19  0.296820            (amazing_lectures, gives_good_feedback)
20  0.300353               (inspirational, gives_good_feedback)
21  0.289753                (gives_good_feedback, tough_grader)
22  0.279152                   (hilarious, gives_good_feedback)
23  0.257951           (get_ready_to_read, gives_good_feedback)
24  0.406360                                (caring, respected)
25  0.254417                    (caring, participation_matters)
26  0.286219                   (caring, clear_grading_criteria)
27  0.272085                               (caring, skip_class)
28  0.286219                         (caring, amazing_lectures)
29  0.300353                            (caring, inspirational)
30  0.300353                                (caring, hilarious)
31  0.268551                 (participation_matters, respected)
32  0.300353                (clear_grading_criteria, respected)
33  0.307420                            (skip_class, respected)
34  0.339223                      (respected, amazing_lectures)
35  0.378092                         (respected, inspirational)
36  0.265018                          (respected, tough_grader)
37  0.332155                             (hilarious, respected)
38  0.254417                         (skip_class, tough_grader)
39  0.282686                  (inspirational, amazing_lectures)
40  0.293286                      (hilarious, amazing_lectures)
41  0.268551                         (hilarious, inspirational)
42  0.307420           (caring, respected, gives_good_feedback)
43  0.257951  (respected, gives_good_feedback, amazing_lectu...
44  0.261484    (inspirational, respected, gives_good_feedback)
45  0.265018                 (caring, respected, inspirational)
46  0.254417                     (caring, hilarious, respected)
47  0.257951           (hilarious, respected, amazing_lectures)

In [ ]:
# GOOD PROFS:
# find association rules that have confidence >= 75%
rules_good_prof = association_rules(frequent_itemsets_good,metric='confidence',min_threshold=0.75)

# print the association rules, their support, and confidence
print(rules_good_prof[['antecedents','consequents','support','confidence']])

                                antecedents            consequents   support  \
0                  (clear_grading_criteria)  (gives_good_feedback)  0.293286
1                  (clear_grading_criteria)            (respected)  0.300353
2                              (skip_class)            (respected)  0.307420
3                        (amazing_lectures)            (respected)  0.339223
4                           (inspirational)            (respected)  0.378092
5                               (hilarious)            (respected)  0.332155
6                       (caring, respected)  (gives_good_feedback)  0.307420
7             (caring, gives_good_feedback)            (respected)  0.307420
8             (respected, amazing_lectures)  (gives_good_feedback)  0.257951
9   (amazing_lectures, gives_good_feedback)            (respected)  0.257951
10     (gives_good_feedback, inspirational)            (respected)  0.261484
11                  (caring, inspirational)            (respected)  0.265018
12                      (caring, hilarious)            (respected)  0.254417
13                   (hilarious, respected)               (caring)  0.254417
14                   (hilarious, respected)     (amazing_lectures)  0.257951
15            (hilarious, amazing_lectures)            (respected)  0.257951
16            (respected, amazing_lectures)            (hilarious)  0.257951

    confidence
0     0.761468
1     0.779817
2     0.763158
3     0.780488
4     0.810606
5     0.770492
6     0.756522
7     0.798165
8     0.760417
9     0.869048
10    0.870588
11    0.882353
12    0.847059
13    0.765957
14    0.776596
15    0.879518
16    0.760417

### *EXPERIMENT 3: High support and Low confidence*

In [ ]:
# GOOD PROFS:
# find all itemsets that have a minimum support of 35%
frequent_itemsets_good = apriori(goodProfsBooleanTags,min_support=0.35,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_good)

     support                          itemsets
0   0.600707             (gives_good_feedback)
1   0.554770                          (caring)
2   0.636042                       (respected)
3   0.388693           (participation_matters)
4   0.385159          (clear_grading_criteria)
5   0.402827                      (skip_class)
6   0.434629                (amazing_lectures)
7   0.466431                   (inspirational)
8   0.416961                    (tough_grader)
9   0.431095                       (hilarious)
10  0.385159     (caring, gives_good_feedback)
11  0.431095  (respected, gives_good_feedback)
12  0.406360               (caring, respected)
13  0.378092        (respected, inspirational)

In [ ]:
# GOOD PROFS:
# find association rules that have confidence >= 10%
rules_good_prof = association_rules(frequent_itemsets_good,metric='confidence',min_threshold=0.1)

# print the association rules, their support, and confidence
print(rules_good_prof[['antecedents','consequents','support','confidence']])

             antecedents            consequents   support  confidence
0               (caring)  (gives_good_feedback)  0.385159    0.694268
1  (gives_good_feedback)               (caring)  0.385159    0.641176
2            (respected)  (gives_good_feedback)  0.431095    0.677778
3  (gives_good_feedback)            (respected)  0.431095    0.717647
4               (caring)            (respected)  0.406360    0.732484
5            (respected)               (caring)  0.406360    0.638889
6            (respected)        (inspirational)  0.378092    0.594444
7        (inspirational)            (respected)  0.378092    0.810606

### *EXPERIMENT 4: High support and High confidence*

In [ ]:
# GOOD PROFS:
# find all itemsets that have a minimum support of 40%
frequent_itemsets_good = apriori(goodProfsBooleanTags,min_support=0.4,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_good)

    support                          itemsets
0  0.600707             (gives_good_feedback)
1  0.554770                          (caring)
2  0.636042                       (respected)
3  0.402827                      (skip_class)
4  0.434629                (amazing_lectures)
5  0.466431                   (inspirational)
6  0.416961                    (tough_grader)
7  0.431095                       (hilarious)
8  0.431095  (respected, gives_good_feedback)
9  0.406360               (caring, respected)

In [ ]:
# GOOD PROFS:
# find association rules that have confidence >= 60%
rules_good_prof = association_rules(frequent_itemsets_good,metric='confidence',min_threshold=0.6)

# print the association rules, their support, and confidence
print(rules_good_prof[['antecedents','consequents','support','confidence']])

             antecedents            consequents   support  confidence
0            (respected)  (gives_good_feedback)  0.431095    0.677778
1  (gives_good_feedback)            (respected)  0.431095    0.717647
2               (caring)            (respected)  0.406360    0.732484
3            (respected)               (caring)  0.406360    0.638889

# **Association Rules: Bad Profs**
4 experiments will be done to understand interesting correlations between Characteristics of Bad Professors

1. Low support and Low confidence
2. Low support and High confidence
3. High support and Low confidence
4. High support and High confidence

###*EXPERIMENT 1: Low support and Low confidence*

In [ ]:
# BAD PROFS:
# find all itemsets that have a minimum support of 10%
frequent_itemsets_bad = apriori(badProfsBooleanTags,min_support=0.10,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_bad)

      support                                           itemsets
0    0.353535                              (gives_good_feedback)
1    0.323232                                           (caring)
2    0.232323                                        (respected)
3    0.343434                            (participation_matters)
4    0.282828                           (clear_grading_criteria)
..        ...                                                ...
364  0.111111  (tough_grader, lecture_heavy, test_heavy, skip...
365  0.101010  (lecture_heavy, test_heavy, get_ready_to_read,...
366  0.111111  (tough_grader, lecture_heavy, test_heavy, get_...
367  0.101010  (lots_of_homework, participation_matters, toug...
368  0.101010  (tough_grader, lecture_heavy, test_heavy, get_...

[369 rows x 2 columns]

In [ ]:
# BAD PROFS:
# find association rules that have confidence >= 10%
rules_bad_prof = association_rules(frequent_itemsets_bad,metric='confidence',min_threshold=0.1)

# print the association rules, their support, and confidence
print(rules_bad_prof[['antecedents','consequents','support','confidence']])

                  antecedents  \
0                    (caring)
1       (gives_good_feedback)
2                 (respected)
3       (gives_good_feedback)
4     (participation_matters)
...                       ...
3301          (lecture_heavy)
3302             (test_heavy)
3303      (get_ready_to_read)
3304             (skip_class)
3305   (graded_by_few_things)

                                            consequents   support  confidence
0                                 (gives_good_feedback)  0.161616    0.500000
1                                              (caring)  0.161616    0.457143
2                                 (gives_good_feedback)  0.151515    0.652174
3                                           (respected)  0.151515    0.428571
4                                 (gives_good_feedback)  0.181818    0.529412
...                                                 ...       ...         ...
3301  (tough_grader, test_heavy, get_ready_to_read, ...  0.101010    0.204082
3302  (tough_grader, lecture_heavy, get_ready_to_rea...  0.101010    0.416667
3303  (tough_grader, lecture_heavy, test_heavy, skip...  0.101010    0.196078
3304  (tough_grader, lecture_heavy, test_heavy, get_...  0.101010    0.185185
3305  (tough_grader, lecture_heavy, test_heavy, get_...  0.101010    0.434783

[3306 rows x 4 columns]

###*EXPERIMENT 2: Low support and High confidence*

In [ ]:
# BAD PROFS:
# find all itemsets that have a minimum support of 25%
frequent_itemsets_bad = apriori(badProfsBooleanTags,min_support=0.25,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_bad)

     support                                          itemsets
0   0.353535                             (gives_good_feedback)
1   0.323232                                          (caring)
2   0.343434                           (participation_matters)
3   0.282828                          (clear_grading_criteria)
4   0.545455                                      (skip_class)
5   0.757576                                    (tough_grader)
6   0.515152                               (get_ready_to_read)
7   0.424242                                (lots_of_homework)
8   0.494949                                   (lecture_heavy)
9   0.292929               (gives_good_feedback, tough_grader)
10  0.494949                        (skip_class, tough_grader)
11  0.343434                   (get_ready_to_read, skip_class)
12  0.292929                    (lots_of_homework, skip_class)
13  0.313131                       (lecture_heavy, skip_class)
14  0.444444                 (get_ready_to_read, tough_grader)
15  0.383838                  (lots_of_homework, tough_grader)
16  0.424242                     (lecture_heavy, tough_grader)
17  0.323232                (lecture_heavy, get_ready_to_read)
18  0.272727                 (lecture_heavy, lots_of_homework)
19  0.333333     (get_ready_to_read, skip_class, tough_grader)
20  0.272727      (lots_of_homework, skip_class, tough_grader)
21  0.292929         (lecture_heavy, skip_class, tough_grader)
22  0.303030  (lecture_heavy, get_ready_to_read, tough_grader)

In [ ]:
# BAD PROFS:
# find association rules that have confidence >= 65%
rules_bad_prof = association_rules(frequent_itemsets_bad,metric='confidence',min_threshold=0.65)

# print the association rules, their support, and confidence
print(rules_bad_prof[['antecedents','consequents','support','confidence']])

                           antecedents          consequents   support  \
0                (gives_good_feedback)       (tough_grader)  0.292929
1                         (skip_class)       (tough_grader)  0.494949
2                       (tough_grader)         (skip_class)  0.494949
3                  (get_ready_to_read)         (skip_class)  0.343434
4                   (lots_of_homework)         (skip_class)  0.292929
5                  (get_ready_to_read)       (tough_grader)  0.444444
6                   (lots_of_homework)       (tough_grader)  0.383838
7                      (lecture_heavy)       (tough_grader)  0.424242
8                      (lecture_heavy)  (get_ready_to_read)  0.323232
9      (get_ready_to_read, skip_class)       (tough_grader)  0.333333
10   (get_ready_to_read, tough_grader)         (skip_class)  0.333333
11          (skip_class, tough_grader)  (get_ready_to_read)  0.333333
12      (lots_of_homework, skip_class)       (tough_grader)  0.272727
13    (lots_of_homework, tough_grader)         (skip_class)  0.272727
14         (lecture_heavy, skip_class)       (tough_grader)  0.292929
15       (lecture_heavy, tough_grader)         (skip_class)  0.292929
16  (lecture_heavy, get_ready_to_read)       (tough_grader)  0.303030
17       (lecture_heavy, tough_grader)  (get_ready_to_read)  0.303030
18   (get_ready_to_read, tough_grader)      (lecture_heavy)  0.303030

    confidence
0     0.828571
1     0.907407
2     0.653333
3     0.666667
4     0.690476
5     0.862745
6     0.904762
7     0.857143
8     0.653061
9     0.970588
10    0.750000
11    0.673469
12    0.931034
13    0.710526
14    0.935484
15    0.690476
16    0.937500
17    0.714286
18    0.681818

###*EXPERIMENT 3: High support and Low confidence*

In [ ]:
# BAD PROFS:
# find all itemsets that have a minimum support of 35%
frequent_itemsets_bad = apriori(badProfsBooleanTags,min_support=0.35,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_bad)

    support                           itemsets
0  0.353535              (gives_good_feedback)
1  0.545455                       (skip_class)
2  0.757576                     (tough_grader)
3  0.515152                (get_ready_to_read)
4  0.424242                 (lots_of_homework)
5  0.494949                    (lecture_heavy)
6  0.494949         (skip_class, tough_grader)
7  0.444444  (get_ready_to_read, tough_grader)
8  0.383838   (lots_of_homework, tough_grader)
9  0.424242      (lecture_heavy, tough_grader)

In [ ]:
# BAD PROFS:
# find association rules that have confidence >= 10%
rules_bad_prof = association_rules(frequent_itemsets_bad,metric='confidence',min_threshold=0.1)

# print the association rules, their support, and confidence
print(rules_bad_prof[['antecedents','consequents','support','confidence']])

           antecedents          consequents   support  confidence
0         (skip_class)       (tough_grader)  0.494949    0.907407
1       (tough_grader)         (skip_class)  0.494949    0.653333
2  (get_ready_to_read)       (tough_grader)  0.444444    0.862745
3       (tough_grader)  (get_ready_to_read)  0.444444    0.586667
4   (lots_of_homework)       (tough_grader)  0.383838    0.904762
5       (tough_grader)   (lots_of_homework)  0.383838    0.506667
6      (lecture_heavy)       (tough_grader)  0.424242    0.857143
7       (tough_grader)      (lecture_heavy)  0.424242    0.560000

###*EXPERIMENT 4: High support and High confidence*

In [ ]:
# BAD PROFS:
# find all itemsets that have a minimum support of 40%
frequent_itemsets_bad = apriori(badProfsBooleanTags,min_support=0.40,use_colnames=1)

# print the itemsets that meet the criteria
print(frequent_itemsets_bad)

    support                           itemsets
0  0.545455                       (skip_class)
1  0.757576                     (tough_grader)
2  0.515152                (get_ready_to_read)
3  0.424242                 (lots_of_homework)
4  0.494949                    (lecture_heavy)
5  0.494949         (skip_class, tough_grader)
6  0.444444  (get_ready_to_read, tough_grader)
7  0.424242      (lecture_heavy, tough_grader)

In [ ]:
# BAD PROFS:
# find association rules that have confidence >= 65%
rules_bad_prof = association_rules(frequent_itemsets_bad,metric='confidence',min_threshold=0.65)

# print the association rules, their support, and confidence
print(rules_bad_prof[['antecedents','consequents','support','confidence']])

           antecedents     consequents   support  confidence
0         (skip_class)  (tough_grader)  0.494949    0.907407
1       (tough_grader)    (skip_class)  0.494949    0.653333
2  (get_ready_to_read)  (tough_grader)  0.444444    0.862745
3      (lecture_heavy)  (tough_grader)  0.424242    0.857143